# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QWidget, QPushButton
from PyQt5.QtGui import QIcon
from PyQt5.QtCore import QTimer
from algorithms import *
from grid import *
import pygame_menu

class Game():
    def __init__(self):
        pygame.init()
        self.game_init()

    # pygame initialization
    def game_init(self):
        self.rows = 50
        self.width = 800
        self.grid = make_grid(self.rows, self.width)

        self.start = None
        self.end = None

        self.win = pygame.display.set_mode((self.width, self.width))
        pygame.display.set_caption("Path visualizer")


    # pygame main loop
    def loop(self, window):
        draw(self.win, self.grid, self.rows, self.width)
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                return True
            
            if pygame.mouse.get_pressed()[0]: # left click
                pos = pygame.mouse.get_pos()
                row, col = get_clicked_pos(pos, self.rows, self.width)
                spot = self.grid[row][col]
                if not self.start and spot != self.end:
                    self.start = spot
                    self.start.make_start()
                    window.set_start(self.start.get_pos()[0], self.start.get_pos()[1])
                elif not self.end and spot != self.start:
                    self.end = spot
                    self.end.make_end()
                    window.set_end(self.end.get_pos()[0], self.end.get_pos()[1])
                elif spot != self.end and spot != self.start:
                    spot.make_barrier()
            elif pygame.mouse.get_pressed()[2]: # right click
                pos = pygame.mouse.get_pos()
                row, col = get_clicked_pos(pos, self.rows, self.width)
                spot = self.grid[row][col]
                spot.reset()
                if spot == self.start:
                    self.start = None
                elif spot == self.end:
                    self.end = None
            if event.type == pygame.KEYDOWN:
                if event.key == pygame.K_SPACE and self.start and self.end:
                    for row in self.grid:
                        for spot in row:
                            spot.update_neighbors(self.grid)

                    dfs(lambda: draw(self.win, self.grid, self.rows, self.width), self.grid, self.start, self.end)

                if event.key == pygame.K_c:
                    self.start = None
                    self.end = None
                    self.grid = make_grid(self.rows, self.width)
        return False



class Ui_MainWindow(object):
    def __init__(self, MainWindow, game):
        super().__init__()
        self.MainWIN = MainWindow
        self.setupUi(MainWindow)
        self.init_pygame(game)
    
    def init_pygame(self, game):
        self.game = game
        self.timer = QTimer()
        self.timer.timeout.connect(self.pygame_loop)
        self.timer.start(0)

    def pygame_loop(self):
        if self.game.loop(self):
            self.MainWIN.close()
        

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(350, 255)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.spinBox_1 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_1.setGeometry(QtCore.QRect(80, 30, 47, 24))
        self.spinBox_1.setMinimum(1)
        self.spinBox_1.setMaximum(50)
        self.spinBox_1.setObjectName("spinBox_1")
        self.spinBox_2 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_2.setGeometry(QtCore.QRect(80, 60, 47, 24))
        self.spinBox_2.setMinimum(1)
        self.spinBox_2.setMaximum(50)
        self.spinBox_2.setObjectName("spinBox_2")
        self.spinBox_3 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_3.setGeometry(QtCore.QRect(80, 90, 47, 24))
        self.spinBox_3.setMinimum(1)
        self.spinBox_3.setMaximum(50)
        self.spinBox_3.setObjectName("spinBox_3")
        self.spinBox_4 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_4.setGeometry(QtCore.QRect(80, 120, 47, 24))
        self.spinBox_4.setMinimum(1)
        self.spinBox_4.setMaximum(50)
        self.spinBox_4.setObjectName("spinBox_4")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(190, 130, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("font: 9pt \"Sans Serif\";\n"
"background-color: rgb(170, 0, 255);\n"
"")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 150, 161, 21))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 30, 59, 15))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 59, 15))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 59, 15))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 120, 59, 15))
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(0, 180, 161, 31))
        self.pushButton.setStyleSheet("background-color: rgb(85, 0, 127);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(180, 20, 151, 61))
        self.pushButton_2.setStyleSheet("background-color: rgb(0, 0, 127);\n"
"font: 75 11pt \"DejaVu Serif\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(150, 20, 31, 141))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(190, 100, 101, 20))
        self.label_5.setObjectName("label_5")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(140, 50, 20, 21))
        self.graphicsView.setStyleSheet("background-color: rgb(255, 165, 0);")
        self.graphicsView.setObjectName("graphicsView")
        self.graphicsView_3 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_3.setGeometry(QtCore.QRect(140, 110, 20, 21))
        self.graphicsView_3.setStyleSheet("background-color: rgb(64, 224, 208);")
        self.graphicsView_3.setObjectName("graphicsView_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 350, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton.clicked.connect(self.find_path)
        self.pushButton_2.clicked.connect(self.gen)
        MainWindow.show()
    
    def gen(self):
        self.game.grid = make_grid(self.game.rows, self.game.width)
        #s_row, s_col = self.spinBox_1.value()-1, self.spinBox_2.value()-1 
        #self.game.start = self.game.grid[s_row][s_col]
        #self.game.start.make_start()
        

        #e_row, e_col = self.spinBox_3.value()-1, self.spinBox_4.value()-1
        #self.game.end = self.game.grid[e_row][e_col]
        #self.game.end.make_end()

        

        for row in self.game.grid:
            for spot in row:
                spot.update_neighbors(self.game.grid)

        maze_gen(lambda: draw(self.game.win, self.game.grid, self.game.rows, self.game.width), self.game.grid, self.game.start, self.game.end)
        self.statusbar.showMessage("Maze generated!")

    def set_start(self, x, y):
        self.spinBox_1.setValue(x+1)
        self.spinBox_2.setValue(y+1)

    def set_end(self, x, y):
        self.spinBox_3.setValue(x+1)
        self.spinBox_4.setValue(y+1)

    def find_path(self):
        
        s_row, s_col = self.spinBox_1.value()-1, self.spinBox_2.value()-1 
        self.game.start = self.game.grid[s_row][s_col]
        self.game.start.make_start()

        e_row, e_col = self.spinBox_3.value()-1, self.spinBox_4.value()-1
        self.game.end = self.game.grid[e_row][e_col]
        self.game.end.make_end()


        for row in self.game.grid:
            for spot in row:
                if not spot.is_barrier() and not spot.is_start() and not spot.is_end() :
                    spot.reset()
                spot.update_neighbors(self.game.grid)
        if self.comboBox.currentText() == "BFS":
            if not bfs(lambda: draw(self.game.win, self.game.grid, self.game.rows, self.game.width), self.game.grid, self.game.start, self.game.end):
                self.statusbar.showMessage("path not found")
        elif self.comboBox.currentText() == "A* Search":
            if not algorithm(lambda: draw(self.game.win, self.game.grid, self.game.rows, self.game.width), self.game.grid, self.game.start, self.game.end):
                self.statusbar.showMessage("path not found")
        elif self.comboBox.currentText() == "DFS":
            if not dfs(lambda: draw(self.game.win, self.game.grid, self.game.rows, self.game.width), self.game.grid, self.game.start, self.game.end):
                self.statusbar.showMessage("path not found")
        elif self.comboBox.currentText() == "Dijkstra":
            if not dijkstra(lambda: draw(self.game.win, self.game.grid, self.game.rows, self.game.width), self.game.grid, self.game.start, self.game.end):
                self.statusbar.showMessage("path not found")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.comboBox.setItemText(0, _translate("MainWindow", "A* Search"))
        self.comboBox.setItemText(1, _translate("MainWindow", "BFS"))
        self.comboBox.setItemText(2, _translate("MainWindow", "DFS"))
        self.comboBox.setItemText(3, _translate("MainWindow", "DIjkstra"))
        self.label.setText(_translate("MainWindow", "Start X"))
        self.label_2.setText(_translate("MainWindow", "Start Y"))
        self.label_3.setText(_translate("MainWindow", "End X"))
        self.label_4.setText(_translate("MainWindow", "End Y"))
        self.pushButton.setText(_translate("MainWindow", "Find Path"))
        self.pushButton_2.setText(_translate("MainWindow", "Generate Maze"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#550000;\">Algorithm</span></p></body></html>"))


if __name__ == "__main__":
    import sys

    game = Game()
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow(MainWindow, game)

    sys.exit(app.exec_())